spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_store?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
      jpa:
    generate-ddl: true
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:      ddl-auto: create