spring:
  application:
    name: 'store'
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
